### ISSUE TITLE
Can't control Chromecast media playback and Android crashes

### ISSUE THREAD

**Issue by bengalih** [jellyfin/jellyfin-chromecast#118]
This is probably related to issues like these:
https://github.com/jellyfin/jellyfin-chromecast/issues/57
https://github.com/jellyfin/jellyfin-chromecast/issues/67

And my original issue that was closed:
https://github.com/jellyfin/jellyfin-chromecast/issues/29
(why my issue was closed instead of the duplicate 67 I have no idea....)

But not the exact parameters.  I'm running the latest 10.7.0 on Windows and 2.2.3 on Android 11.
I just upgraded from 10.6.1 to 10.7.0 because I was/am still experiencing issues with my Google Mini/Nest products not reporting anything playing when Cast to them from JF.
Casting is usually started from Chrome on Windows, though the issue appears regardless of how I can get the cast to happen.
This means that the Google devices not only can't pause/ff/rw, etc, but they don't even register that media is playing if you say "Ok Google, what's playing?" and you cannot stop playback via voice, you are required to open up the JF app and terminate playback which is a huge drawback when you need to take a call, etc.

I researched the issues above after upgrading to 10.7.0 and after changing the the Playback Chromecast version to Nightly (and refreshing, and starting playback from a new incognito session, etc), nothing has changed.  The Google devices still don't recognize any media playing from JF.

Additionally, this problem is conflated with 2.2.3 of the Android app.  When Chromecast version is set to stable, everything works normal (albeit the issue at hand of not being able to control playback).  However, if I use the Nightly version then the Android app will crash on playback.  Specifically what happens is after choosing the cast location and then beginning playback the media controls will show on the screen but no playback will happen (i.e. the counter stays a 0:00).  If you attempt to press play again or skip forward or otherwise interact, the entire app crashes.

The only reason I care about this is that it appears the only way to get the Google devices to register the media is to use the Nightly version.  Additionally, I am unable to get this to work from Chrome on Windows.  Therefore, I am still having the same issues as #29 and #67 and both have been closed.

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: none
 - Clients: Latest Chrome on Windows, Android 2.2.3,  Google Mini/Nest clients.
 - Browser: Chrome  89.0.4389.82
 - Jellyfin Version: 10.7.0
 - Playback: any
 - Installed Plugins: none
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: host
 - Storage: local

**Comment by ferferga** [comment]
That issue was indeed a duplicate.

Did you close and reopened the Jellyfin tab after setting chromecast to unstable version?

**Comment by bengalih** [comment]
> That issue was indeed a duplicate.
> 
> Did you close and reopened the Jellyfin tab after setting chromecast to unstable version?

Yes - the issue wasn't that it was a duplicate, the issue was that my issue was the original one logged.  It would make sense to me that future issues be tagged as duplicate and the original is used as the ongoing issue.  Doing it otherwise doesn't seem to make sense to me.  For one, I had no insight into the tracking of that issue because it was basically closed and work was continued on a new ticket.

And yes, I closed and reopened JF tab.  As I state in my issue above I actually reopened a new tab via incognito as was recommended in another thread.

**Comment by ferferga** [comment]
@YouKnowBlom It's been out for a while so I have no idea why he closed that issue instead, I guess bc he considered that, for tracking purposes, it described the issue better than yours, but I don't know :).

I doubt you're running unstable because controls work flawlessly on it. Might want to reboot the cast device and try again. You can send me an screenshot so I can confirm you if the version you're using is indeed unstable, but I doubt it because everything you mention doesn't apply to the state of unstable.

Unstable is unstable for a reason though. Right now work is halted bc I don't have any cast devices around (they're in another house and here we're confined) and Blom and @hawken93 have been busy with their daily lives.

All that unstable needs to be pushed to stable branch is queue support and polishing these kind of quirks you're experiencing. If you want to contribute to development it would be really appreciated, as chromecast has been the step-child lately.

**Comment by bengalih** [comment]
What specifically do you need a screen shot of or how can I confirm it is using unstable?  I changed it, saved, relaunched and have tried to multiple cast devices that hadn't used any version of JF in months.  I can reboot when I try again later tonight.

However this doesn't explain the total android client crashes when set to unstable either...other than the fact that I must be properly switching it as I only experience the no playback/crashes when I have toggled to unstable.  So that would seem to reinforce the fact that I have swapped correctly.

I'm not sure I can assist much with development, but I'm happy to run whatever tests are required to track down issues.  Please let me know what other info I can provide to solve.

Right now I'm mostly concerned with just getting the cast from Chrome to work with media awareness via unstable.  Though I'm happy to continue tracking down issue with android client as well.

**Comment by bengalih** [comment]
Closing this down in lieu of https://github.com/jellyfin/jellyfin-chromecast/issues/351
