### ISSUE TITLE
Media buttons don't work

### ISSUE THREAD

**Issue by surdu** [jellyfin/jellyfin-chromecast#12]
The Play/Pause/Stop buttons from my TV remote doesn't work with Jellyfin chromecast app. It works ok with any other Chromecast app.

If anybody can point me in the right directions of how to run a dev environment for Chromecast apps, I could take a shot at fixing this issue.

**Comment by anthonylavado** [comment]
To develop on Chromecast:
* Sign up here, pay $5 fee https://developers.google.com/cast/
* Host the web app somewhere it can be reached (even as a github page should work)
* Create a Cast app pointing to the hosted site
* Register your Chromecast as a developer device
* Clone Jellyfin, change the APP ID to your custom one
* Build and run Jellyfin

**Comment by anthonylavado** [comment]
That said, we'll still try to look at this ourselves 😄

Thank you for filing it!

**Comment by surdu** [comment]
@anthonylavado Managed to complete all the steps, but I'm slightly stuck. When you say "Build and run Jellyfin", you mean the server? The server dictates what the Chromecast app is ?

**Comment by anthonylavado** [comment]
@surdu Sorry for seeing this so late. In the jellyfin-web submodule that is part of the server, there is a "ChromecastPlayer.js" file. This contains the APP ID that the Chromecast will use.

Here's the exact location:
https://github.com/jellyfin/jellyfin-web/blob/5c96a86f90cf38b28d50549285c35063efc139e4/src/components/chromecast/chromecastplayer.js#L57

So I guess you could change this in your local install and you should be fine.

**Comment by surdu** [comment]
@anthonylavado Managed to do all that, bit it appears that I'm having a problem with Jellyfin web app not showing the Chromecast entry in the `Play On` menu :(. 

I've posted a comment [here](https://github.com/jellyfin/jellyfin-web/issues/32#issuecomment-515797137), hopefully people there have some pointers for me.

In the mean time, I'll try to build the Android application and use that.

**Comment by surdu** [comment]
... just can't catch a break:  managed to build the android app, but just shows a black screen after it opens 😞

**Comment by nasazh** [comment]
This is still happening. Shall this be reopened or do you need a new issue?
