### ISSUE TITLE
Chromecast Play/Pause support via HDMI-CEC

### ISSUE THREAD

**Issue by pceiley** [jellyfin/jellyfin-chromecast#13]
This is a very highly desired feature for me - allows me to use my TV remote to quickly play/pause videos playing via the Chromecast.

**Comment by JustAMan** [comment]
@pceiley I've transferred your issue as I don't think it belongs to Android app, more like to Chromecast itself. Feel free to disagree with me if I got your issue wrongly.

**Comment by Ebbe** [comment]
I can see that the code is merged, but is it also released? If so, it is still not working for me. How can I see what version the Chromecast app has?

**Comment by YouKnowBlom** [comment]
> I can see that the code is merged, but is it also released? If so, it is still not working for me. How can I see what version the Chromecast app has?

It is not released yet. Soon you'll be able to switch "Chromecast version" to "nightly" under playback settings. 

(You may already see the toggle but nightly is still running the same version as stable for now)
