### ISSUE TITLE
Subtitles display twice

### ISSUE THREAD

**Issue by sirber** [jellyfin/jellyfin-chromecast#27]
![image](https://user-images.githubusercontent.com/3911428/79459489-5afa7300-7fc1-11ea-8d97-f9d08e1795b4.png)

Server Version: 10.5.3

From the android client

**Comment by YouKnowBlom** [comment]
Are you running the CAF receiver or the old one? 

(If you haven't modified anything in jellyfin-web then it should be the old one)
