### ISSUE TITLE
Does not respond to HDMI-CEC playback controls

### ISSUE THREAD

**Issue by LinAGKar** [jellyfin/jellyfin-chromecast#364]
**Describe the bug**

Jellyfin on Chromecast does not respond to playback controls on the TV remote, sent over HDMI-CEC

**To Reproduce**

1. Play something from Jellyfin on Chromecast
2. Make sure CEC is connected
3. Press pause on the TV remote

**Expected behavior**

The video pauses

**System:**

-   OS: Docker
-   Jellyfin Version: 10.8.0-beta1
-   Cast client: gen 2

**Comment by neopc10** [comment]
#53

**Comment by BloodyIron** [comment]
> #53

How exactly is that relevant? I don't see CEC mentioned once. Is this still the case of it being broken @LinAGKar ?

**Comment by LinAGKar** [comment]
Nothing seems to have changed. Stable Chromecast still doesn't respond to CEC, unstable Chromecast still doesn't work at all

**Comment by cvium** [comment]
We're unfortunately in dire need of a maintainer for the CC client. The active members of the Jellyfin team do not use CC, so there's little incentive.

**Comment by daprahamian** [comment]
IS there any way I could help get this moving? I'm not super experienced with the ecosystem, but I use almost exclusively Chromecast and would like to be able to control playback with my TV remote. This issue combined with https://github.com/jellyfin/jellyfin-web/issues/3541 means that I frequently wind up in a situation where video is playing on my TV and I have no way to pause it.

**Comment by nielsvanvelzen** [comment]
The only way to get it moving is to fix the bug yourself or find someone to do it. We don't have any contributors for casting support right now.

**Comment by nielsvanvelzen** [comment]
Closing as duplicate of #53.

I'd also like to remind everyone that we currently do not have any contributors for the cast receiver.

**Comment by 3flex** [comment]
This should be reopened, it's distinct from #53 - this was mentioned above, and the HDMI-CEC issue is still present.
