### ISSUE TITLE
Casting music to a Chromecast Audio, wrong track plays and playback stops after the track

### ISSUE THREAD

**Issue by adrianedworthy** [jellyfin/jellyfin-chromecast#375]
**Describe the bug**
When casting music to Chromecast Audio using the Android app, no matter what track you pick the first track on the album is played. After that it stops. You can add songs to the playlist, but they will not play afterwards.

If you click on the play button on an album it will then play the full album through in order.

**System (please complete the following information):**
 - OS: Android.
 - Virtualization: Nope.
 - Clients: Android.
 - Jellyfin Version: 10.5.4

**To Reproduce**

1. Cast to a Chromecast Audio
2. Click on a track other than the first on an album
3. Watch it play the first track on the album

**Expected behavior**
It should play the track you choose.

**Comment by yanfali** [comment]
still broken on chromecast... sad

**Comment by ginger-tek** [comment]
> still broken on chromecast... sad

Same here 😞

**Comment by neopc10** [comment]
This can likely be closed thanks to #465

**Comment by nielsvanvelzen** [comment]
Closing as fixed. If you still encounter this issue check if your "Google Cast Version" is set to unstable first. If it is, please create a new issue.
