### ISSUE TITLE
No support for IPv6

### ISSUE THREAD

**Issue by lucasmz-dev** [jellyfin/jellyfin-chromecast#404]
When trying to connect to an IPv6-only server, the connection fails.

**To Reproduce**

1. Connect to an IPv6-only server
2. The app will load on Chromecast, but playing won't work and there's not even a film image as the background for the app.

**Expected behavior**

The connection should work just fine, basic functionality should just work.

-   OS: Android 12
-   Browser: Chrome
-   Jellyfin version: 10.8.10
-   Cast Receiver version: Stable
-   Cast client: Chromecast 2 Standard

**Additional context**

The domain name has A records, these are for Tailscale and for a fallback IPv6-only warning. 

IPv6 support on Chromecast itself is something I'm unsure of. There are changelogs that indicate Chromecast supports IPv6 but people have had issues testing it, it's hard to figure that out based on singular apps because what if the app itself doesn't support it? 

Using Web Vídeo Caster worked, but it was being proxied through my phone. When using an IPv4 supported domain, it plays directly. But then, what if Web Vídeo Caster just doesn't support it like Jellyfin? What if it's some library both of them use? I'm unsure.

This update would indicate there is support. https://chromereleases.googleblog.com/2014/04/chromecast-update.html

I am on a SLAAC environment, DNS on DHCPv6, though this shouldn't be an issue because you can get AAAA records from V4 DNS.

**Comment by 3flex** [comment]
My understanding is that Google has never publicly declared support for IPv6 on any Chromecast device they've sold, except the Google TV Streamer launched this year (see below). The release notes you linked could mean almost anything - potentially it was about improving compatibility when the devices are used on dual stack networks.

Unless you can find an official statement or support page saying Google supports IPv6 on Chromecast devices (I also have a Chromecast 2, and never found any evidence it supports IPv6), then this should be closed.

Even the Google TV Streamer (4K) tech specs don't mention IPv6 support: https://store.google.com/product/google_tv_streamer_specs?hl=en-GB

However Google states it supports Matter protocol, which operates over IPv6, so it will have some level of native IPv6 support. But Chromecast 2 does not.

**Comment by lucasmz-dev** [comment]
I'm not really using Jellyfin anymore (or Chromecast) so I'll close this anyway :P 

> Even the Google TV Streamer (4K) tech specs don't mention IPv6 support: https://store.google.com/product/google_tv_streamer_specs?hl=en-GB

Stupid Google only sells Google Home officially here, link doesn't even work smh
