### ISSUE TITLE
Transcoded 2160p content not played on Chromecast

### ISSUE THREAD

**Issue by bertmelis** [jellyfin/jellyfin-chromecast#502]
Playback of a 2160p movie doesn't work on Chromecast. It works for my laptop for examples, where to file is also transcoded.
It starts transcoding but never writes the temporary file so nothing can be served to the client.

The screen stays black and after a while, it returns to the Jellyfin main waiting screen.

When transcoding a file that works, somewhere in the transcode log there is a line like this:
```
[hls @ 0x55ffe34ac9c0] Opening '/config/transcodes/63e1f251f3303081e824d9b49857592c13.ts' for writing
```

For -amongst others- this file, nothing is written.

**Media Info of the file**
```
Video
Title: 4K HEVC SDR
Codec: HEVC
Profile: Main 10
Level: 150
Resolution: 3840x1604
Aspect ratio: 2.40:1
Interlaced: No
Framerate: 23.976025
Bitrate: 6392 kbps
Bit depth: 10 bit
Video range: SDR
Video range type: SDR
Pixel format: yuv420p10le
Ref frames: 1

Audio
Title: AAC - 5.1 - Default
Codec: AAC
Profile: LC
Layout: 5.1
Channels: 6 ch
Bitrate: 320 kbps
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No
```

**Logs**
```
[2022-12-16 10:16:42.305 +00:00] [INF] [51] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="/media/movies/[redacted].mkv", AudioStreamIndex=3, SubtitleStreamIndex=0 ) => ( PlayMethod=Transcode, TranscodeReason=VideoCodecNotSupported ) "media:/videos/67410726-e76d-6573-fafa-30236ca28e14/stream.mkv?MediaSourceId=67410726e76d6573fafa30236ca28e14&VideoCodec=h264,vp8&AudioCodec=aac&AudioStreamIndex=3&VideoBitrate=19616000&AudioBitrate=384000&AudioSampleRate=48000&MaxFramerate=23.976025&api_key=<token>&TranscodingMaxAudioChannels=2&CopyTimestamps=true&RequireAvc=false&Tag=463d00ec5c20103acd828b6cff3935d1&hevc-level=150&hevc-videobitdepth=10&hevc-profile=main10&hevc-audiochannels=6&aac-profile=lc&h264-profile=high,main,baseline,constrainedbaseline&h264-level=42&aac-audiochannels=2&TranscodeReasons=VideoCodecNotSupported"
[2022-12-16 10:16:42.574 +00:00] [INF] [138] Jellyfin.Api.Helpers.TranscodingJobHelper: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -init_hw_device vaapi=va:,driver=iHD,kernel_driver=i915 -init_hw_device qsv=qs@va -filter_hw_device qs -autorotate 0 -i file:\"/media/movies/[redacted].mkv\" -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_qsv -force_key_frames \"expr:gte(t,n_forced*5)\" -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,min(3840\,1634*a))/2)*2:trunc(min(max(iw/a\,ih)\,min(3840/a\,1634))/2)*2,format=yuv420p\" -copyts -avoid_negative_ts disabled -start_at_zero -low_power 1 -preset 7 -look_ahead 0 -b:v 11097215 -maxrate 11097215 -bufsize 22194430 -profile:v:0 high -level 42 -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 libfdk_aac -ac 2 -ab 384000 -ar 48000 -af \"volume=2\" -y \"/config/transcodes/d1d1e9ba6237f3b6af0fe21b198359a3.mkv\""
[2022-12-16 10:17:16.297 +00:00] [INF] [115] Jellyfin.Api.Helpers.TranscodingJobHelper: Transcoding kill timer stopped for JobId "11b408ad0d5949d597e2a7a4edbcb07c" PlaySessionId "bbbfd77c22be4136bfc3d61e0e24be97". Killing transcoding
[2022-12-16 10:17:16.297 +00:00] [INF] [115] Jellyfin.Api.Helpers.TranscodingJobHelper: Stopping ffmpeg process with q command for "/config/transcodes/d1d1e9ba6237f3b6af0fe21b198359a3.mkv"
[2022-12-16 10:17:16.501 +00:00] [INF] [115] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 0
[2022-12-16 10:17:16.501 +00:00] [INF] [115] Jellyfin.Api.Helpers.TranscodingJobHelper: Deleting partial stream file(s) "/config/transcodes/d1d1e9ba6237f3b6af0fe21b198359a3.mkv"
```

**FFmpeg Logs**
```
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_qsv))
  Stream #0:1 -> #0:1 (aac (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
Output #0, matroska, to '/config/transcodes/99b6282df9e16b365917a39468144d72.mkv':
  Metadata:
    encoder         : Lavf59.27.100
  Stream #0:0: Video: h264 (H264 / 0x34363248), nv12(tv, bt709, progressive), 3840x1604 [SAR 1:1 DAR 960:401], q=2-31, 10616 kb/s, 23.98 fps, 1k tbn (default)
    Metadata:
      encoder         : Lavc59.37.100 h264_qsv
    Side data:
      cpb: bitrate max/min/avg: 10616000/0/10616000 buffer size: 21232000 vbv_delay: N/A
  Stream #0:1: Audio: aac ([255][0][0][0] / 0x00FF), 48000 Hz, stereo, s16, 384 kb/s (default)
    Metadata:
      encoder         : Lavc59.37.100 libfdk_aac
frame=    1 fps=0.0 q=0.0 size=       1kB time=00:00:00.00 bitrate=N/A speed=   0x    
frame=   16 fps=0.0 q=26.0 size=       1kB time=00:00:00.66 bitrate=   9.3kbits/s speed=1.11x    
frame=   41 fps= 37 q=16.0 size=       1kB time=00:00:01.68 bitrate=   3.6kbits/s speed=1.52x    
frame=   65 fps= 40 q=10.0 size=       1kB time=00:00:02.68 bitrate=   2.3kbits/s speed=1.66x    
frame=   87 fps= 41 q=12.0 size=       1kB time=00:00:03.60 bitrate=   1.7kbits/s speed= 1.7x    
frame=  109 fps= 42 q=12.0 size=    5120kB time=00:00:04.52 bitrate=9273.3kbits/s speed=1.72x    
frame=  129 fps= 41 q=12.0 size=    5120kB time=00:00:05.37 bitrate=7801.9kbits/s speed=1.71x    
frame=  152 fps= 42 q=12.0 size=    5120kB time=00:00:06.33 bitrate=6619.8kbits/s speed=1.74x    
frame=  176 fps= 42 q=10.0 size=    5120kB time=00:00:07.31 bitrate=5731.5kbits/s speed=1.76x    
frame=  201 fps= 43 q=10.0 size=   10240kB time=00:00:08.36 bitrate=10030.6kbits/s speed=1.79x    
frame=  227 fps= 44 q=10.0 size=   10240kB time=00:00:09.45 bitrate=8875.9kbits/s speed=1.83x    
frame=  253 fps= 45 q=14.0 size=   10240kB time=00:00:10.53 bitrate=7959.6kbits/s speed=1.86x    
frame=  278 fps= 45 q=14.0 size=   13312kB time=00:00:11.58 bitrate=9414.0kbits/s speed=1.87x    
frame=  305 fps= 45 q=26.0 size=   13312kB time=00:00:12.71 bitrate=8576.6kbits/s speed=1.89x    
frame=  332 fps= 46 q=17.0 size=   13312kB time=00:00:13.82 bitrate=7888.6kbits/s speed=1.91x    
frame=  357 fps= 46 q=17.0 size=   18432kB time=00:00:14.87 bitrate=10154.3kbits/s speed=1.93x    
frame=  383 fps= 47 q=17.0 size=   18432kB time=00:00:15.95 bitrate=9462.0kbits/s speed=1.94x    

[q] command received. Exiting.

frame=  383 fps= 46 q=17.0 Lsize=   20828kB time=00:00:16.02 bitrate=10649.3kbits/s speed=1.94x    
video:20057kB audio:761kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.045356%
```

**Server System (please complete the following information):**
 - OS: Podman on Rocky Linux
 - Jellyfin Version: 10.8.8
 - Hardware settings & device: QSV enabled on J4105 (other transcodes work fine)
 - Reverse proxy: Nginx, also containerized
 
**Client System (please complete the following information):**
- non-4k Chromecast

**Comment by keypunch** [comment]
Adding my 2 cents here - having this issue with a Chromecast HD.
Android TV OS 12
Patch level Apr 1, 2024
Kernel version: 5.4.259-android12-9-g95db6f1dfeac
Android TV OS build : STTE.240315.002

FFMPEG log:
`{
    "Protocol": 0,
    "Id": "9b2f44ffe92c55b6ccb6856ac1b0053c",
    "Path": "******-2160p.mkv",
    "EncoderPath": null,
    "EncoderProtocol": null,
    "Type": 0,
    "Container": "mkv",
    "Size": 7530207473,
    "Name": "******",
    "IsRemote": false,
    "ETag": "7239b7d24b95eb1bb23394434a6953e3",
    "RunTimeTicks": 94300270000,
    "ReadAtNativeFramerate": false,
    "IgnoreDts": false,
    "IgnoreIndex": false,
    "GenPtsInput": false,
    "SupportsTranscoding": true,
    "SupportsDirectStream": true,
    "SupportsDirectPlay": true,
    "IsInfiniteStream": false,
    "RequiresOpening": false,
    "OpenToken": null,
    "RequiresClosing": false,
    "LiveStreamId": null,
    "BufferMs": null,
    "RequiresLooping": false,
    "SupportsProbing": true,
    "VideoType": 0,
    "IsoType": null,
    "Video3DFormat": null,
    "MediaStreams": [
        {
            "Codec": "hevc",
            "CodecTag": null,
            "Language": null,
            "ColorRange": null,
            "ColorSpace": "bt709",
            "ColorTransfer": "bt709",
            "ColorPrimaries": "bt709",
            "DvVersionMajor": null,
            "DvVersionMinor": null,
            "DvProfile": null,
            "DvLevel": null,
            "RpuPresentFlag": null,
            "ElPresentFlag": null,
            "BlPresentFlag": null,
            "DvBlSignalCompatibilityId": null,
            "Comment": null,
            "TimeBase": "1/1000",
            "CodecTimeBase": null,
            "Title": "",
            "VideoRange": 1,
            "VideoRangeType": 1,
            "VideoDoViTitle": null,
            "AudioSpatialFormat": 0,
            "LocalizedUndefined": null,
            "LocalizedDefault": null,
            "LocalizedForced": null,
            "LocalizedExternal": null,
            "LocalizedHearingImpaired": null,
            "DisplayTitle": "4K HEVC SDR",
            "NalLengthSize": null,
            "IsInterlaced": false,
            "IsAVC": false,
            "ChannelLayout": null,
            "BitRate": 6388280,
            "BitDepth": 10,
            "RefFrames": 1,
            "PacketLength": null,
            "Channels": null,
            "SampleRate": null,
            "IsDefault": true,
            "IsForced": false,
            "IsHearingImpaired": false,
            "Height": 1600,
            "Width": 3832,
            "AverageFrameRate": 23.976025,
            "RealFrameRate": 23.976025,
            "Profile": "Main 10",
            "Type": 1,
            "AspectRatio": "2.40:1",
            "Index": 0,
            "Score": null,
            "IsExternal": false,
            "DeliveryMethod": null,
            "DeliveryUrl": null,
            "IsExternalUrl": null,
            "IsTextSubtitleStream": false,
            "SupportsExternalStream": false,
            "Path": null,
            "PixelFormat": "yuv420p10le",
            "Level": 150,
            "IsAnamorphic": false
        },
        {
            "Codec": "aac",
            "CodecTag": null,
            "Language": null,
            "ColorRange": null,
            "ColorSpace": null,
            "ColorTransfer": null,
            "ColorPrimaries": null,
            "DvVersionMajor": null,
            "DvVersionMinor": null,
            "DvProfile": null,
            "DvLevel": null,
            "RpuPresentFlag": null,
            "ElPresentFlag": null,
            "BlPresentFlag": null,
            "DvBlSignalCompatibilityId": null,
            "Comment": null,
            "TimeBase": "1/1000",
            "CodecTimeBase": null,
            "Title": "",
            "VideoRange": 0,
            "VideoRangeType": 0,
            "VideoDoViTitle": null,
            "AudioSpatialFormat": 0,
            "LocalizedUndefined": null,
            "LocalizedDefault": "Default",
            "LocalizedForced": null,
            "LocalizedExternal": "External",
            "LocalizedHearingImpaired": null,
            "DisplayTitle": "AAC - 5.1 - Default",
            "NalLengthSize": null,
            "IsInterlaced": false,
            "IsAVC": false,
            "ChannelLayout": "5.1",
            "BitRate": 320000,
            "BitDepth": null,
            "RefFrames": null,
            "PacketLength": null,
            "Channels": 6,
            "SampleRate": 48000,
            "IsDefault": true,
            "IsForced": false,
            "IsHearingImpaired": false,
            "Height": null,
            "Width": null,
            "AverageFrameRate": null,
            "RealFrameRate": null,
            "Profile": "LC",
            "Type": 0,
            "AspectRatio": null,
            "Index": 1,
            "Score": null,
            "IsExternal": false,
            "DeliveryMethod": null,
            "DeliveryUrl": null,
            "IsExternalUrl": null,
            "IsTextSubtitleStream": false,
            "SupportsExternalStream": false,
            "Path": null,
            "PixelFormat": null,
            "Level": 0,
            "IsAnamorphic": null
        },
        {
            "Codec": "subrip",
            "CodecTag": null,
            "Language": "eng",
            "ColorRange": null,
            "ColorSpace": null,
            "ColorTransfer": null,
            "ColorPrimaries": null,
            "DvVersionMajor": null,
            "DvVersionMinor": null,
            "DvProfile": null,
            "DvLevel": null,
            "RpuPresentFlag": null,
            "ElPresentFlag": null,
            "BlPresentFlag": null,
            "DvBlSignalCompatibilityId": null,
            "Comment": null,
            "TimeBase": "1/1000",
            "CodecTimeBase": null,
            "Title": "",
            "VideoRange": 0,
            "VideoRangeType": 0,
            "VideoDoViTitle": null,
            "AudioSpatialFormat": 0,
            "LocalizedUndefined": "Undefined",
            "LocalizedDefault": "Default",
            "LocalizedForced": "Forced",
            "LocalizedExternal": "External",
            "LocalizedHearingImpaired": "Hearing Impaired",
            "DisplayTitle": "English - Default - SUBRIP",
            "NalLengthSize": null,
            "IsInterlaced": false,
            "IsAVC": false,
            "ChannelLayout": null,
            "BitRate": null,
            "BitDepth": null,
            "RefFrames": null,
            "PacketLength": null,
            "Channels": null,
            "SampleRate": null,
            "IsDefault": true,
            "IsForced": false,
            "IsHearingImpaired": false,
            "Height": 0,
            "Width": 0,
            "AverageFrameRate": null,
            "RealFrameRate": null,
            "Profile": null,
            "Type": 2,
            "AspectRatio": null,
            "Index": 2,
            "Score": null,
            "IsExternal": false,
            "DeliveryMethod": null,
            "DeliveryUrl": null,
            "IsExternalUrl": null,
            "IsTextSubtitleStream": true,
            "SupportsExternalStream": true,
            "Path": null,
            "PixelFormat": null,
            "Level": 0,
            "IsAnamorphic": null
        },
        {
            "Codec": "subrip",
            "CodecTag": null,
            "Language": "fre",
            "ColorRange": null,
            "ColorSpace": null,
            "ColorTransfer": null,
            "ColorPrimaries": null,
            "DvVersionMajor": null,
            "DvVersionMinor": null,
            "DvProfile": null,
            "DvLevel": null,
            "RpuPresentFlag": null,
            "ElPresentFlag": null,
            "BlPresentFlag": null,
            "DvBlSignalCompatibilityId": null,
            "Comment": null,
            "TimeBase": "1/1000",
            "CodecTimeBase": null,
            "Title": "French",
            "VideoRange": 0,
            "VideoRangeType": 0,
            "VideoDoViTitle": null,
            "AudioSpatialFormat": 0,
            "LocalizedUndefined": "Undefined",
            "LocalizedDefault": "Default",
            "LocalizedForced": "Forced",
            "LocalizedExternal": "External",
            "LocalizedHearingImpaired": "Hearing Impaired",
            "DisplayTitle": "French - SUBRIP",
            "NalLengthSize": null,
            "IsInterlaced": false,
            "IsAVC": false,
            "ChannelLayout": null,
            "BitRate": null,
            "BitDepth": null,
            "RefFrames": null,
            "PacketLength": null,
            "Channels": null,
            "SampleRate": null,
            "IsDefault": false,
            "IsForced": false,
            "IsHearingImpaired": false,
            "Height": 0,
            "Width": 0,
            "AverageFrameRate": null,
            "RealFrameRate": null,
            "Profile": null,
            "Type": 2,
            "AspectRatio": null,
            "Index": 3,
            "Score": null,
            "IsExternal": false,
            "DeliveryMethod": null,
            "DeliveryUrl": null,
            "IsExternalUrl": null,
            "IsTextSubtitleStream": true,
            "SupportsExternalStream": true,
            "Path": null,
            "PixelFormat": null,
            "Level": 0,
            "IsAnamorphic": null
        }
    ],
    "MediaAttachments": [],
    "Formats": [],
    "Bitrate": 6708280,
    "Timestamp": null,
    "RequiredHttpHeaders": {},
    "TranscodingUrl": null,
    "TranscodingSubProtocol": 0,
    "TranscodingContainer": null,
    "AnalyzeDurationMs": null,
    "DefaultAudioStreamIndex": null,
    "DefaultSubtitleStreamIndex": null
}`

This log section repeats a few times:
`[2024-08-14 18:50:28.889 -06:00] [INF] [39] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: "ffmpeg" "-analyzeduration 200M -probesize 1G -f matroska -noautorotate -i file:\"******-2160p.mkv\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -preset veryfast -crf 23 -maxrate 5170833 -bufsize 10341666 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames:0 \"expr:gte(t,n_forced*3)\" -sc_threshold:v:0 0 -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,min(3840\,1604*a))/2)*2:trunc(min(max(iw/a\,ih)\,min(3840/a\,1604))/2)*2,format=yuv420p\" -codec:a:0 libfdk_aac -ac 6 -ab 640000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename \"C:\ProgramData\Jellyfin\Server\cache\transcodes\c9535febcd57444da59fea0376e3efe2%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"C:\ProgramData\Jellyfin\Server\cache\transcodes\c9535febcd57444da59fea0376e3efe2.m3u8\""
[2024-08-14 18:50:29.909 -06:00] [INF] [26] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Android TV" "0.17.3" playing "******". Stopped at "0" ms
[2024-08-14 18:50:30.611 -06:00] [INF] [31] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for "C:\ProgramData\Jellyfin\Server\cache\transcodes\c9535febcd57444da59fea0376e3efe2.m3u8"
[2024-08-14 18:50:30.615 -06:00] [INF] [25] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "home". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-08-14 18:50:30.788 -06:00] [INF] [25] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[2024-08-14 18:50:30.788 -06:00] [INF] [31] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) "C:\ProgramData\Jellyfin\Server\cache\transcodes\c9535febcd57444da59fea0376e3efe2.m3u8"`

Finally ending with:
`[2024-08-14 18:50:34.480 -06:00] [INF] [35] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Android TV" "0.17.3" playing "******". Stopped at "0" ms
[2024-08-14 18:51:39.566 -06:00] [INF] [17] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-08-14 18:51:46.529 -06:00] [WRN] [25] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "10.0.0.99" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2024-08-14 18:51:46.548 -06:00] [INF] [25] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "10.0.0.99" closed
[2024-08-14 18:52:02.231 -06:00] [INF] [35] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "home". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True`

**Comment by GodTamIt** [comment]
Just curious: are people here plugging a non-4K Chromecast into a 4K TV or screen?

**Comment by GodTamIt** [comment]
Actually, https://github.com/jellyfin/jellyfin/pull/12499 might've fixed this change.

**Comment by keypunch** [comment]
> Just curious: are people here plugging a non-4K Chromecast into a 4K TV or screen?

I'll keep an eye out to see if it's changed, but no, definitely a 1080p TV (Samsung un43n5300)

**Comment by bertmelis** [comment]
That would be great!

I see it's included in the latest release so it's straighforward to try it out. I will see if I can test it this evening, on an old HD television with an HD chromecast.

**Comment by bertmelis** [comment]
> Actually, [jellyfin/jellyfin#12499](https://github.com/jellyfin/jellyfin/pull/12499) might've fixed this issue.

I tested and it now works!

**Comment by dd-ugm** [comment]
Just in case anyone is still suffering this issue despite [jellyfin/jellyfin#12499](https://github.com/jellyfin/jellyfin/pull/12499). This reappeared randomly for me after a long while of not having to deal with it. 

I'm running the linuxserver.io docker image on an Intel i5-7500 and I had the openCL docker mod enabled via my compose file. But as the processor is a legacy CPU in terms of the graphics, openCL is only supported through one specific version of the docker mod – if this version is not specified, openCL fails and playback aborts.

linuxserver/jellyfin at [jellyfin-opencl-intel](https://github.com/linuxserver/docker-mods/tree/jellyfin-opencl-intel):
> If your system is equipped with an older CPU, you will need to pin the Opencl-Intel mod to a specific version. Intel has deprecated support for "legacy" CPUs with pre-Tigerlake GPUs. This includes desktop CPUs prior to Rocketlake, laptop CPUs prior to Tigerlake, and low power CPUs prior to Alderlake-N. If you are unsure which CPU family you have, if your iGPU model number is in the 500 and 600 range, you have a "legacy" Intel CPU.
> 
> For legacy CPUs, you must pin the Opencl-Intel mod to version 24.35.30872.22. Versions newer than this will cause tone mapping in Jellyfin to fail due to the openCL runtime not supporting your legacy CPU. Appending the environment variable with the version number will install that specific version. DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel-24.35.30872.22

Modified my compose file and voila! Hope this helps a few folks out.
