### ISSUE TITLE
Chromecast is remuxing/transcode for unknown reason since version 10.9.2

### ISSUE THREAD

**Issue by Alliyance** [jellyfin/jellyfin-chromecast#583]
My friend is connected to my server and he use Chromecast HD, 0.16.11. All my files are programmed the same way (H264, 8 bit, AAC 5.1 6ch 48000Hz, SRT subs, bitrate 5000) It was always direct stream but since version 10.9.2, I get the FFmpeg and in the log file, usually it says the transcode reason but there's none. He use a soundbar which is the same since a year and all was direct stream before. Any idea why Jellfyfin is reacting this way? His sister has the same Chromecast but her is direct stream, no soundbar. 

Note: 
That was with jellyfin server 10.9.4.
Just update to the latest version, waiting if that wiill help.
On Linux
Chromecast HD 0.16.11
Stable

**Logs*
`[2024-06-27 23:51:34.295 +00:00] [INF] [143] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "fred". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: False
[2024-06-27 23:51:34.426 +00:00] [INF] [42] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "fred". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: False
[2024-06-27 23:51:35.261 +00:00] [INF] [143] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: "/usr/bin/ffmpeg" "-analyzeduration 200M -probesize 1G -fflags +genpts -f matroska  -i file:\"/home/alliyance/files/Movies/Furiosa.A.Mad.Max.Saga.2024.mkv\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename \"/dev/shm/1011/jellyfin/transcodes/3830c672dc2466dcbde6df2872984be7%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/dev/shm/1011/jellyfin/transcodes/3830c672dc2466dcbde6df2872984be7.m3u8\""
[2024-06-27 23:51:36.186 +00:00] [INF] [248] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for "/dev/shm/1011/jellyfin/transcodes/3830c672dc2466dcbde6df2872984be7.m3u8"
[2024-06-27 23:51:36.263 +00:00] [INF] [248] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[2024-06-27 23:51:36.267 +00:00] [INF] [248] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: "/usr/bin/ffmpeg" "-analyzeduration 200M -probesize 1G -ss 00:10:07.148 -fflags +genpts -f matroska  -i file:\"/home/alliyance/files/Movies/Furiosa.A.Mad.Max.Saga.2024.mkv\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 101 -hls_segment_filename \"/dev/shm/1011/jellyfin/transcodes/3830c672dc2466dcbde6df2872984be7%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/dev/shm/1011/jellyfin/transcodes/3830c672dc2466dcbde6df2872984be7.m3u8\""
[2024-06-27 23:51:45.383 +00:00] [INF] [231] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Completed after 0 minute(s) and 16 seconds
[2024-06-27 23:51:45.474 +00:00] [INF] [257] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/home/alliyance/files/Documentary movies"
[2024-06-27 23:51:45.475 +00:00] [INF] [61] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/home/alliyance/files/Clients"
[2024-06-27 23:51:45.475 +00:00] [INF] [143] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/home/alliyance/files/Movies"
[2024-06-27 23:51:45.475 +00:00] [INF] [42] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/home/alliyance/files/Documentary series"
[2024-06-27 23:51:45.480 +00:00] [INF] [328] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/home/alliyance/files/Series"
[2024-06-27 23:52:12.878 +00:00] [INF] [257] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0`

FFmpeg:

`/usr/bin/ffmpeg -analyzeduration 200M -probesize 1G -ss 01:38:49.465 -fflags +genpts -f matroska  -i file:"/home/alliyance/files/Movies/Furiosa.A.Mad.Max.Saga.2024.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 988 -hls_segment_filename "/dev/shm/1011/jellyfin/transcodes/b12401affdf65f854659892e1e0f4e93%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/dev/shm/1011/jellyfin/transcodes/b12401affdf65f854659892e1e0f4e93.m3u8"

ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13 (Gentoo Hardened 13.2.1_p20240210 p14)
  configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --docdir=/usr/share/doc/ffmpeg-6.1.1-r5/html --mandir=/usr/share/man --enable-shared --cc=x86_64-pc-linux-gnu-gcc --cxx=x86_64-pc-linux-gnu-g++ --ar=x86_64-pc-linux-gnu-ar --nm=x86_64-pc-linux-gnu-nm --strip=x86_64-pc-linux-gnu-strip --ranlib=x86_64-pc-linux-gnu-ranlib --pkg-config=x86_64-pc-linux-gnu-pkg-config --optflags='-O3 -pipe -march=native -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing' --enable-static --disable-libaribcaption --enable-avfilter --disable-stripping --disable-optimizations --disable-libcelt --enable-nonfree --disable-indev=v4l2 --disable-outdev=v4l2 --disable-indev=alsa --disable-indev=oss --disable-indev=jack --disable-indev=sndio --disable-outdev=alsa --disable-outdev=oss --disable-outdev=sndio --enable-bzlib --disable-runtime-cpudetect --disable-debug --disable-gcrypt --enable-gnutls --disable-gmp --enable-gpl --disable-hardcoded-tables --enable-iconv --disable-libxml2 --disable-lzma --enable-network --disable-opencl --enable-openssl --enable-postproc --disable-libsmbclient --disable-ffplay --disable-sdl2 --disable-vaapi --disable-vdpau --disable-vulkan --disable-xlib --disable-libxcb --disable-libxcb-shm --disable-libxcb-xfixes --enable-zlib --disable-libcdio --disable-libiec61883 --disable-libdc1394 --disable-libcaca --disable-openal --disable-opengl --disable-libv4l2 --disable-libpulse --disable-libdrm --disable-libjack --disable-libopencore-amrwb --disable-libopencore-amrnb --disable-libcodec2 --enable-libdav1d --disable-libfdk-aac --disable-libopenjpeg --disable-libjxl --enable-libbluray --disable-libgme --disable-libgsm --disable-libaribb24 --disable-libmodplug --disable-libopus --disable-libvpl --disable-libilbc --disable-librtmp --disable-libssh --disable-libspeex --disable-libsrt --disable-librsvg --disable-ffnvcodec --enable-libvorbis --disable-libvpx --disable-libzvbi --disable-appkit --disable-libbs2b --enable-chromaprint --disable-cuda-llvm --disable-libflite --disable-fontconfig --disable-frei0r --disable-libfribidi --disable-libglslang --disable-ladspa --disable-lcms2 --enable-libass --disable-libplacebo --disable-libtesseract --disable-lv2 --disable-librubberband --disable-libshaderc --disable-libfreetype --disable-libharfbuzz --disable-libvidstab --disable-libvmaf --disable-libzmq --disable-libzimg --disable-libsoxr --enable-pthreads --disable-amf --disable-libvo-amrwbenc --disable-libkvazaar --disable-libaom --enable-libmp3lame --disable-libopenh264 --disable-librav1e --disable-libsnappy --disable-libsvtav1 --disable-libtheora --disable-libtwolame --disable-libwebp --enable-libx264 --enable-libx265 --disable-libxvid --disable-gnutls --enable-version3 --disable-armv5te --disable-armv6 --disable-armv6t2 --disable-neon --disable-vfp --disable-vfpv3 --disable-armv8 --disable-dotprod --disable-i8mm --disable-mipsdsp --disable-mipsdspr2 --disable-mipsfpu --disable-altivec --disable-vsx --disable-power8 --disable-amd3dnow --disable-amd3dnowext --disable-fma4 --disable-xop --enable-pic --cpu=host --enable-lto=auto --disable-doc --disable-htmlpages --enable-manpages
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Input #0, matroska,webm, from 'file:/home/alliyance/files/Movies/Furiosa.A.Mad.Max.Saga.2024.mkv':
  Metadata:
    encoder         : libebml v1.4.5 + libmatroska v1.7.1
    creation_time   : 2024-06-25T11:47:16.000000Z
  Duration: 02:28:11.88, start: 0.000000, bitrate: 5933 kb/s
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x800 [SAR 1:1 DAR 12:5], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS             : 5039092
      DURATION        : 02:28:11.758000000
      NUMBER_OF_FRAMES: 213189
      NUMBER_OF_BYTES : 5600798767
      _STATISTICS_WRITING_APP: mkvmerge v84.0 ('Sleeper') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2024-06-25 11:47:16
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: aac (LC), 48000 Hz, 5.1, fltp (default)
    Metadata:
      BPS             : 445371
      DURATION        : 02:28:11.818000000
      NUMBER_OF_FRAMES: 416804
      NUMBER_OF_BYTES : 495019772
      _STATISTICS_WRITING_APP: mkvmerge v84.0 ('Sleeper') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2024-06-25 11:47:16
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(fre): Audio: aac (LC), 48000 Hz, 5.1, fltp
    Metadata:
      BPS             : 445371
      DURATION        : 02:28:11.882000000
      NUMBER_OF_FRAMES: 416807
      NUMBER_OF_BYTES : 495023335
      _STATISTICS_WRITING_APP: mkvmerge v84.0 ('Sleeper') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2024-06-25 11:47:16
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(eng): Subtitle: subrip
    Metadata:
      title           : Full
      BPS             : 27
      DURATION        : 02:16:58.580000000
      NUMBER_OF_FRAMES: 1050
      NUMBER_OF_BYTES : 28752
      _STATISTICS_WRITING_APP: mkvmerge v84.0 ('Sleeper') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2024-06-25 11:47:16
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(fre): Subtitle: subrip (forced)
    Metadata:
      title           : Forced
      BPS             : 1
      DURATION        : 02:19:36.451000000
      NUMBER_OF_FRAMES: 57
      NUMBER_OF_BYTES : 1941
      _STATISTICS_WRITING_APP: mkvmerge v84.0 ('Sleeper') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2024-06-25 11:47:16
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:5(fre): Subtitle: subrip
    Metadata:
      title           : Full
      BPS             : 25
      DURATION        : 02:27:40.560000000
      NUMBER_OF_FRAMES: 1043
      NUMBER_OF_BYTES : 28037
      _STATISTICS_WRITING_APP: mkvmerge v84.0 ('Sleeper') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2024-06-25 11:47:16
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[out#0/hls @ 0x55aa722d2c40] Codec AVOption threads (set the number of threads) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Output #0, hls, to '/dev/shm/1011/jellyfin/transcodes/b12401affdf65f854659892e1e0f4e93.m3u8':
  Metadata:
    encoder         : Lavf60.16.100
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x800 [SAR 1:1 DAR 12:5], q=2-31, 23.98 fps, 23.98 tbr, 90k tbn (default)
  Stream #0:1: Audio: aac (LC), 48000 Hz, 5.1, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
size=       0kB time=00:00:00.00 bitrate=N/A speed=N/A    
[hls @ 0x55aa7226f080] Non-monotonic DTS in output stream 0:0; previous: 533603070, current: 533599316; changing to 533603071. This may result in incorrect timestamps in the output file.
[hls @ 0x55aa7226f080] Non-monotonic DTS in output stream 0:0; previous: 533603071, current: 533603070; changing to 533603072. This may result in incorrect timestamps in the output file.
[hls @ 0x55aa7226f080] Opening '/dev/shm/1011/jellyfin/transcodes/b12401affdf65f854659892e1e0f4e93988.ts' for writing`

**Comment by nielsvanvelzen** [comment]
> 0.16.11

Are you sure you're using the chromecast receiver and not the Android TV app?

**Comment by Alliyance** [comment]
It's the app. I guess I posted in the wrong place.

**Comment by Alliyance** [comment]
It's a Chromecast with the android tv app 0.16.11 on it.

**Comment by nielsvanvelzen** [comment]
You can find the Android TV app [here](https://github.com/jellyfin/jellyfin-androidtv). Make sure there is no existing similar issue before creating a new one.
