### ISSUE TITLE
Receiver always starts playback from the beginning

### ISSUE THREAD

**Issue by YouKnowBlom** [jellyfin/jellyfin-chromecast#63]
**Describe the bug**
Receiver always starts playback from the beginning, despite resuming previously played item from web

**To Reproduce**

1. Play previously played item with progress
2. Watch as the receiver will start playing from the beginning

**Expected behavior**

Resume from the correct tick

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.6.4 (unstable)
 - Cast client: Gen 2

**Comment by hawken93** [comment]
Personally I'm blaming this: https://github.com/jellyfin/jellyfin-chromecast/blob/1528f3dd998ad80b3b85a32e552dfd08a03e847b/src/helpers.js#L179
This function gets called way too much and I think maybe it resets the ticks.

**Comment by neopc10** [comment]
#107
