### ISSUE TITLE
chromecast playback can't be controlled via google home 

### ISSUE THREAD

**Issue by lambchop01** [jellyfin/jellyfin-chromecast#67]
Maybe this is a feature request not a bug.  If so create the issue there.
**Describe the bug**
When Jellyfin is playing media on my chromecast, I cannot control playback with google home.  I also do not get a notification on my phone telling me that there is media playing on the chromecast.  For all other applications streaming media through the chromecast (netflix, youtube, etc.) I can simply say "hey google, pause the tv".  With jellyfin though google just tells me there is currently no media playing.

**System (please complete the following information):**
 - OS: Debian (Lubuntu)
 - Virtualization: Docker
 - Clients: Browser, Android, google devices(chromecast, home minis)
 - Browser: Chrome
 - Jellyfin Version: 10.6.4
 - Playback: [irect Play 
 - Installed Plugins: none
 - Reverse Proxy: no
 - Base URL: none
 - Networking: Bridge/NAT
 - Storage: local

**To Reproduce**

1. start media playback on google home device
2. ask google device to pause playback
3. google tells me there is no media playing on device

**Expected behavior**

I expect playback to pause

**Logs**

**Screenshots**

**Additional context**

**Comment by hamburglar2160** [comment]
I don't think you're using the new Cast receiver that says "Jellyfin for Google Cast." If you were, the bug would be on Google's side.

**Comment by lambchop01** [comment]
How would I check?

**Comment by YouKnowBlom** [comment]
@lambchop01 Sorry for the late response. I've updated the unstable receiver to show a more accurate version in the format of `3.0.0-<Date>.<Revision>`. If you check the active devices in the jf-web dashboard you should be able to see a version number similar to that format, else you're on the old version.

**Comment by lambchop01** [comment]
No problem! Ill take a look when i get a chance.
I'm running in docker, i assume ill have to pull the latest, or recent nightly builds?

**Comment by ferferga** [comment]
@lambchop01 You don't, just switch to "Unstable" Chromecast version in Playback settings (under your user menu) and you're good to go!

**Comment by lambchop01** [comment]
Just tried it. 
Stable shows chromecast 2.1.0 as a client. Casting works as normal. No recognized playback execpt through the jellyfin android app (2.2.0).  
Switch to nightly, saved. force closed the app and restarted the server to be sure. chromecast loads jellyfin but crashes when attempting to start playback. It also still shows chromecast 2.1.0 as the client in the admin dashboard.

**Comment by ferferga** [comment]
@lambchop01 Mind trying in web instead?

Make sure that your user's playback preferences are set to Chromecast unstable. Make sure you hit save when changing it. 

Then, open F12 and right click in the reload button. Choose last option (Force reload and clear cache I think it's called). Try casting now, you should see Chromecast receiver version 3.0.

If that doesn't work, try using Incognito tab so we're sure that all local data of web is cleared up (not sure if casting works there though, but iirc it should)

**Comment by lambchop01** [comment]
So, short answer, that worked! Kinda.

I had the clear cache and hard reload the page after saving the "nightly" chromecast option.  Then i could cast normally through the android app. It showed version 3.x.x, and google told me there was something playing on my tv!
Yippie! Thanks!

Maybe a separate issue entirely, I cant cast from the web ui.  Connecting directly through ipaddress:8096, none of my google devices show up as cast options. Interesting to note though, that using the android app I access the server this way.
When connecting through my reverse proxy, they show up, but the server receives no feedback upon connection and so nothing ever plays (i suspect it requires nat loopback, due to googles hardcoded dns servers).

**Comment by ferferga** [comment]
@lambchop01 Looks like you're hitting a well-known issue from 10.6 that will be fixed in 10.7

 jellyfin/jellyfin-web#2085

**Comment by lambchop01** [comment]
@ferferga Awesome! I can wait until then.
Thanks for all your help!

**Comment by ferferga** [comment]
@lambchop01 I'll close this as the main issue discussed here it's resolved.

Thanks for all the troubleshooting!
