### ISSUE TITLE
[Question] Where do the bits from the "nightly" chromecast client come from? Do I have to update my local copy?

### ISSUE THREAD

**Issue by SteveDinn** [jellyfin/jellyfin-chromecast#75]
I'd love to help test the Chromecast app. I have always thought that the app was loaded from my installed Jellyfin instance is this the case? Or is it loaded from somewhere in the cloud? If I pick "nightly" as my Chromecast version in the web client, where do these 'nightly' bits come from?

I'm seeing all these commits and I'm eager to try them out

Thanks!

**Comment by nielsvanvelzen** [comment]
The cast client is loaded from jellyfin.org. This is a limitation on Google's side.

**Comment by SteveDinn** [comment]
Hrm...so even though my server is local the cast client has to come from the cloud? That's unfortunate. Are all these commits actually going to be in the "nightly" builds? What's the best way to tell what version (or what commit) of the Chromecast client that actually loads?

**Comment by nielsvanvelzen** [comment]
I'm quite sure the master branch is what you get when you use the nightly builds. The stable build is quite old I think.
@YouKnowBlom should know better then I do though.

**Comment by YouKnowBlom** [comment]
Indeed, the unstable option always points to master.

There's no great way to see any specifics if other than if you're on stable or unstable. I've been thinking of editing the CI to include the commit hash somewhere but I haven't gotten around to it yet

**Comment by YouKnowBlom** [comment]
I've now added a bit more detail to the version string reported to the server. Currently it looks like this `3.0.0_<date>.<rev>`. Finding the exact revision is a bit tricky as you have to look through the CI but the date should at least give a better idea.

You should be able to check the version in the active devices section of the dashboard now :+1:

**Comment by YouKnowBlom** [comment]
Closing this as I feel the question has been answered
