### ISSUE TITLE
Typescript migration

### ISSUE THREAD

**Issue by YouKnowBlom** [jellyfin/jellyfin-chromecast#80]
Opening this issue to track progress on the ongoing typescript migration:

- [x] `src/app.js`
- [x] `src/helpers.js`
- [x] `src/components/castDevices.js`
- [x] `src/components/codecSupportHelper.js`
- [x] `src/components/commandHandler.js`
- [x] `src/components/deviceprofileBuilder.js`
- [x] `src/components/fetchhelper.js`
- [x] `src/components/jellyfinActions.js`
- [x] `src/components/maincontroller.js`
- [x] `src/components/playbackManager.js`

**Comment by neopc10** [comment]
\o/

**Comment by ferferga** [comment]
Finished on #99, needs to add typings and JSDoc. Partial work done on #106

**Comment by YouKnowBlom** [comment]
Closing this as all boxes have been ticked 🚀
